# Generated by Django 5.2.7 on 2026-01-12 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_productgallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="variation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="store.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variation",
            unique_together={("product", "variation_category", "variation_value")},
        ),
    ]
