# Generated by Django 5.2.7 on 2026-01-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_variation_stock_alter_variation_product_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="variation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.product"
            ),
        ),
        migrations.RemoveField(
            model_name="variation",
            name="stock",
        ),
    ]
