# Generated by Django 5.2.7 on 2026-01-12 17:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_variation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="variation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("variation_value"),
                models.F("product"),
                models.F("variation_category"),
                name="unique_variation_value_per_product_and_category",
            ),
        ),
    ]
