# Generated by Django 5.2.7 on 2026-01-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_variation_unique_variation_value_per_product_and_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
