# Generated by Django 5.2.7 on 2026-01-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_product_discount_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount_price",
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
