# Generated by Django 5.2.7 on 2026-01-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        ("store", "0007_variation_unique_variation_value_per_product_and_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReport",
            fields=[],
            options={
                "verbose_name": "Product Report",
                "verbose_name_plural": "Product Reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.product",),
        ),
        migrations.DeleteModel(
            name="MonthlySalesReport",
        ),
    ]
