# Generated by Django 5.2.7 on 2026-01-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_productreport_delete_monthlysalesreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Sales Summary", max_length=100)),
            ],
            options={
                "verbose_name": "Sales Summary",
                "verbose_name_plural": "Sales Summary",
            },
        ),
    ]
