# Generated by Django 5.2.7 on 2026-01-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_salessummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="salessummary",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
