# Generated by Django 5.2.7 on 2026-01-13 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_salessummary_created_at"),
        ("store", "0007_variation_unique_variation_value_per_product_and_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRatingReport",
            fields=[],
            options={
                "verbose_name": "Review Rating Report",
                "verbose_name_plural": "Review Rating Reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.reviewrating",),
        ),
        migrations.CreateModel(
            name="TopCustomerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Top Customer Report",
                "verbose_name_plural": "Top Customers Report",
            },
        ),
    ]
