# Generated by Django 5.2.7 on 2026-01-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
        ("reports", "0005_reviewratingreport_topcustomerreport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TopCustomerReport",
        ),
        migrations.CreateModel(
            name="TopCustomerReport",
            fields=[],
            options={
                "verbose_name": "Top Customer Report",
                "verbose_name_plural": "Top Customers Report",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.account",),
        ),
    ]
