# Generated by Django 5.2.7 on 2026-01-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_delete_topcustomerreport_topcustomerreport"),
        ("store", "0007_variation_unique_variation_value_per_product_and_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="LowStockReport",
            fields=[],
            options={
                "verbose_name": "Low Stock Report",
                "verbose_name_plural": "Low Stock Reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.product",),
        ),
    ]
