# Generated by Django 5.2.7 on 2026-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash On Delivery", "Cash On Delivery"),
                    ("SSLcommerz", "SSLcommerz"),
                ],
                default="Cash On Delivery",
                max_length=50,
            ),
        ),
    ]
