# Generated by Django 5.2.7 on 2026-01-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash On Delivery", "Cash On Delivery"),
                    ("Credit Card", "Credit Card"),
                    ("PayPal", "PayPal"),
                ],
                default="Cash On Delivery",
                max_length=50,
            ),
        ),
    ]
