# Generated by Django 5.2.7 on 2026-01-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash On Delivery", "Cash On Delivery"),
                    ("SSLcommerz", "SSLcommerz"),
                ],
                default="Cash On Delivery",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=100),
        ),
    ]
