# Generated by Django 5.2.7 on 2026-01-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_payment_method_alter_payment_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
    ]
