# Generated by Django 5.2.7 on 2026-01-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_payment_method"),
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="variation",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
