# Generated by Django 5.2.7 on 2026-01-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_orderproduct_variation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
    ]
