# Generated by Django 5.2.7 on 2026-01-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_orderproduct_color_remove_orderproduct_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_area",
            field=models.CharField(
                choices=[("inside", "Inside Dhaka"), ("outside", "Outside Dhaka")],
                default="inside",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_charge",
            field=models.DecimalField(decimal_places=2, default=80, max_digits=10),
        ),
    ]
