# Generated by Django 5.2.7 on 2026-01-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_delivery_area_order_delivery_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="discount_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
