# Generated by Django 5.2.7 on 2026-01-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_orderproduct_discount_percent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="discount_percent",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="original_price",
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product_price",
            field=models.FloatField(),
        ),
    ]
