# Generated by Django 5.2.7 on 2026-01-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_orderproduct_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="estimated_delivery",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Accepted",
                max_length=10,
            ),
        ),
    ]
