# Generated by Django 5.2.7 on 2026-01-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_estimated_delivery_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
